# ワークフローの名前
name: sample workflow

# ワークフローを実行するトリガー
on: 
  push: 
    # mainブランチにpushしたとき
    branches: ["main"] 
  pull_request:
    # 新しくmainブランチでpull requestが作成されたとき
    branches: ["main"]
  # 明示的に実行ボタンを押したとき
  workflow_dispatch: 

# ワークフローで実行される一連の処理
jobs:
  # ジョブの一つ
  build:
    # どのような仮想環境でジョブの処理を動かすを定義
    runs-on: ubuntu-latest

    # 処理のステップ
    steps:
      # 外部で定義されたアクションを呼び出している
      # actions/checkout@v3は自分自身のリポジトリのデータを読み込む
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug
          
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: Execute PHPUnit Tests
        run: vendor/bin/phpunit --coverage-text

      - name: Run a one-line script
        run: echo start build

      - name: Run a multi-line script
        run:
          echo Add other actions to build,
          echo test, and deploy your project.
